### ISSUE TITLE
excess file in project

### ISSUE THREAD

**Issue by slabousAndrey** [SerdzhyoVashchuk/Bouncy#3]
excess file `run.bat` in the root of the project.
maybe, we should add these file formats to the `gitignore` file.
WDYT?

**Comment by SerdzhyoVashchuk** [comment]
> excess file `run.bat` in the root of the project.
> maybe, we should add these file formats to the `gitignore` file.
> WDYT?

File run.bat has been deleted.
This file was really not necessary.

Thank you for your concern
